services:
  frontend:
    container_name: eneo-frontend
    build:
      context: ./eneo-chatbot-frontend

    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - eneo
      - mcp-net

  backend:
    container_name: eneo-backend
    build:
      context: ./eneo-chatbot-api-backend
    expose:
      - "3001"
    env_file:
      - ./eneo-chatbot-api-backend/.env
    restart: unless-stopped
    networks:
      - eneo

networks:
  eneo:
    driver: bridge

  mcp-net:
    external: true
